project:
  type: book
  output-dir: docs

book:
  title: "Kevin's Coding Resources"
  subtitle: "Resources for Statistics and Econometrics"
  author: "Kevin Lingfeng Li"
  search: false
  chapters:
    - text: "Welcome!"
      href: index.qmd
    - text: "---"
    - syntax.qmd
    - import.qmd
    - data.qmd
    - stats.qmd
    - plot.qmd
    - text: "---"
    - reg.qmd
    - ds.qmd
    - metrics.qmd
    


format:
  html:
    theme: default
    fontsize: 11.5pt
    css: styles.css
    highlight-style: github
    grid:
      sidebar-width: 220px
      body-width: 850px
      margin-width: 210px
    number-depth: 1
    html-math-method: mathjax
    crossref:
      eq-prefix: eq.
      def-prefix: definition
      thm-prefix: theorem
    toc: true
    toc-depth: 4
    include-in-header:
      text: |
        <script src="mathjax-config.js"></script>
    include-after-body:
      text: |
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">


editor: visual

